'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("StrelyCleannerPro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _127_1274197_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_127_1274197_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CLASSES_ROOT\Directory\shell\OpenWithCMD]
        '''@=&quot;Open Command Prompt here&quot;
        '''&quot;Icon&quot;=&quot;cmd.exe&quot;
        '''&quot;NoWorkingDirectory&quot;=&quot;&quot;
        '''
        '''[HKEY_CLASSES_ROOT\Directory\shell\OpenWithCMD\command]
        '''@=&quot;cmd.exe /s /k pushd \&quot;%V\&quot;&quot;
        '''
        '''[HKEY_CLASSES_ROOT\Directory\Background\shell\OpenWithCMD]
        '''@=&quot;Open Command Prompt here&quot;
        '''&quot;Icon&quot;=&quot;cmd.exe&quot;
        '''&quot;NoWorkingDirectory&quot;=&quot;&quot;
        '''
        '''[HKEY_CLASSES_ROOT\Directory\Background\shell\OpenWithCMD\command]
        '''@=&quot;cmd.exe /s /k pushd \&quot;%V\&quot;&quot;
        '''
        '''[HKEY_CLASSES_ROOT\Drive\shell\OpenWit [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AddOpenWithCMD() As String
            Get
                Return ResourceManager.GetString("AddOpenWithCMD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CLASSES_ROOT\DesktopBackground\Shell\DesktopShortcuts]
        '''&quot;MUIVerb&quot;=&quot;Desktop Shortcuts&quot;
        '''&quot;SubCommands&quot;=&quot;theme;wallpaper;scrnsavr;desktopicons;sound;cursor;DPI;color&quot;
        '''&quot;icon&quot;=&quot;desk.cpl&quot;
        '''&quot;Position&quot;=-
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\theme]
        '''@=&quot;Change Theme&quot;
        '''&quot;icon&quot;=&quot;imageres.dll,145&quot;
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\theme\command]
        '''@=&quot;control desk [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DesktopShortcuts() As String
            Get
                Return ResourceManager.GetString("DesktopShortcuts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rem USE AT OWN RISK AS IS WITHOUT WARRANTY OF ANY KIND !!!!!
        '''
        '''rem https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/security-malware-windows-defender-disableantispyware
        '''rem &quot;DisableAntiSpyware&quot; is discontinued and will be ignored on client devices, as of the August 2020 (version 4.18.2007.8) update to Microsoft Defender Antivirus.
        '''
        '''rem Disable Tamper Protection First !!!!!
        '''rem https://www.tenforums.com/tutorials/123792-turn-off-tamper-protection-windows-defender-antivirus.html
        '''reg [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DisableDefenderSafeMode1903Plus() As String
            Get
                Return ResourceManager.GetString("DisableDefenderSafeMode1903Plus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedapplications]
        '''&quot;accesssolution&quot;=dword:00000001
        '''&quot;olksolution&quot;=dword:00000001
        '''&quot;onenotesolution&quot;=dword:00000001
        '''&quot;pptsolution&quot;=dword:00000001
        '''&quot;projectsolution&quot;=dword:00000001
        '''&quot;publishersolution&quot;=dword:00000001
        '''&quot;visiosolution&quot;=dword:00000001
        '''&quot;wdsolution&quot;=dword:00000001
        '''&quot;xlsolution&quot;=dword:00000001
        ''' 
        '''[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedsolutiontypes]
        '''&quot;agave&quot;=dword:0000000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DisableOfficeTelemetry() As String
            Get
                Return ResourceManager.GetString("DisableOfficeTelemetry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot;
        '''schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot; /disable
        '''schtasks /end /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot;
        '''schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot; /disable
        '''.
        '''</summary>
        Friend ReadOnly Property DisableOfficeTelemetryTasks() As String
            Get
                Return ResourceManager.GetString("DisableOfficeTelemetryTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot;
        '''schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot; /disable
        '''schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot;
        '''schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot; /disable
        '''schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask&quot;
        '''schtasks /change /tn &quot;\Microsoft\Windo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DisableTelemetryTasks() As String
            Get
                Return ResourceManager.GetString("DisableTelemetryTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot;
        '''schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot; /disable
        '''schtasks /end /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot;
        '''schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot; /disable
        '''.
        '''</summary>
        Friend ReadOnly Property DisableXboxTasks() As String
            Get
                Return ResourceManager.GetString("DisableXboxTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedapplications]
        '''&quot;accesssolution&quot;=-
        '''&quot;olksolution&quot;=-
        '''&quot;onenotesolution&quot;=-
        '''&quot;pptsolution&quot;=-
        '''&quot;projectsolution&quot;=-
        '''&quot;publishersolution&quot;=-
        '''&quot;visiosolution&quot;=-
        '''&quot;wdsolution&quot;=-
        '''&quot;xlsolution&quot;=-
        ''' 
        '''[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedsolutiontypes]
        '''&quot;agave&quot;=-
        '''&quot;appaddins&quot;=-
        '''&quot;comaddins&quot;=-
        '''&quot;documentfiles&quot;=-
        '''&quot;templatefiles&quot;=-
        '''.
        '''</summary>
        Friend ReadOnly Property EnableOfficeTelemetry() As String
            Get
                Return ResourceManager.GetString("EnableOfficeTelemetry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot; /enable
        '''schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot; /enable
        '''.
        '''</summary>
        Friend ReadOnly Property EnableOfficeTelemetryTasks() As String
            Get
                Return ResourceManager.GetString("EnableOfficeTelemetryTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot; /enable
        '''schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot; /enable
        '''schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask&quot; /enable
        '''schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip&quot; /enable
        '''schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Uploader&quot; /enable
        '''schtasks / [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EnableTelemetryTasks() As String
            Get
                Return ResourceManager.GetString("EnableTelemetryTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot; /enable
        '''schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot; /enable
        '''.
        '''</summary>
        Friend ReadOnly Property EnableXboxTasks() As String
            Get
                Return ResourceManager.GetString("EnableXboxTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ipconfig /release
        '''ipconfig /renew
        '''arp -d *
        '''nbtstat -R
        '''nbtstat -RR
        '''ipconfig /flushdns
        '''ipconfig /registerdns.
        '''</summary>
        Friend ReadOnly Property FlushDNSCache() As String
            Get
                Return ResourceManager.GetString("FlushDNSCache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off 
        '''pushd &quot;%~dp0&quot; 
        '''dir /b %SystemRoot%\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientExtensions-Package~3*.mum &gt;List.txt 
        '''dir /b %SystemRoot%\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientTools-Package~3*.mum &gt;&gt;List.txt 
        '''for /f %%i in (&apos;findstr /i . List.txt 2^&gt;nul&apos;) do dism /online /norestart /add-package:&quot;%SystemRoot%\servicing\Packages\%%i&quot; 
        '''.
        '''</summary>
        Friend ReadOnly Property GPEditEnablerInHome() As String
            Get
                Return ResourceManager.GetString("GPEditEnablerInHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property hosts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("hosts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_biohazard_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_biohazard_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_chrome_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_chrome_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_protect_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_protect_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_puzzle_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_puzzle_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_warning_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_warning_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CLASSES_ROOT\*\shell\runas]
        '''@=&quot;Take Ownership&quot;
        '''&quot;NoWorkingDirectory&quot;=&quot;&quot;
        '''
        '''[HKEY_CLASSES_ROOT\*\shell\runas\command]
        '''@=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F&quot;
        '''&quot;IsolatedCommand&quot;=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F&quot;
        '''
        '''[HKEY_CLASSES_ROOT\Directory\shell\runas]
        '''@=&quot;Take Ownership&quot;
        '''&quot;NoWorkingDirectory&quot;=&quot;&quot;
        '''
        '''[HKEY_CLASSES_ROOT\Directory\shell\runas\command]
        '''@=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; /r /d y &amp;&amp; icacls \&quot;% [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property InstallTakeOwnership() As String
            Get
                Return ResourceManager.GetString("InstallTakeOwnership", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OneDrive_Uninstaller() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OneDrive_Uninstaller", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CLASSES_ROOT\DesktopBackground\Shell\Power Menu]
        '''&quot;MUIVerb&quot;=&quot;Power Menu&quot;
        '''&quot;SubCommands&quot;=&quot;lock;logoff;switch;sleep;hibernate;restart;safemode;shutdown;hybridshutdown&quot;
        '''&quot;Icon&quot;=&quot;shell32.dll,215&quot;
        '''&quot;Position&quot;=&quot;bottom&quot;
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\lock]
        '''@=&quot;Lock&quot;
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\lock\command]
        '''@=&quot;Rundll32 User32.dll,LockWorkStati [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PowerMenu() As String
            Get
                Return ResourceManager.GetString("PowerMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''
        '''[-HKEY_CLASSES_ROOT\*\shell\runas]
        '''
        '''[-HKEY_CLASSES_ROOT\Directory\shell\runas]
        '''.
        '''</summary>
        Friend ReadOnly Property RemoveTakeOwnership() As String
            Get
                Return ResourceManager.GetString("RemoveTakeOwnership", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CLASSES_ROOT\DesktopBackground\Shell\SystemShortcuts]
        '''&quot;MUIVerb&quot;=&quot;System Shortcuts&quot;
        '''&quot;SubCommands&quot;=&quot;admintools;datetime;regional;folderoptions;gmode;internetoptions;network;power;appwiz;rbin;run;search;services;sysdm;user;user2;flip3d&quot;
        '''&quot;icon&quot;=&quot;sysdm.cpl&quot;
        '''&quot;Position&quot;=-
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\admintools]
        '''@=&quot;Administrative Tools&quot;
        '''&quot;icon&quot;=&quot;imageres.dll,109&quot;
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Micros [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SystemShortcuts() As String
            Get
                Return ResourceManager.GetString("SystemShortcuts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CLASSES_ROOT\DesktopBackground\Shell\SystemTools]
        '''&quot;MUIVerb&quot;=&quot;System Tools&quot;
        '''&quot;SubCommands&quot;=&quot;control;cleanmgr;devmgr;event;regedit;secctr;msconfig;taskmgr;taskschd;wu&quot;
        '''&quot;icon&quot;=&quot;imageres.dll,104&quot;
        '''&quot;Position&quot;=-
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\control]
        '''@=&quot;Control Panel&quot;
        '''&quot;icon&quot;=&quot;control.exe&quot;
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\control\command]
        '''@=&quot;c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SystemTools() As String
            Get
                Return ResourceManager.GetString("SystemTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Registry Editor Version 5.00
        '''
        '''[HKEY_CLASSES_ROOT\DesktopBackground\Shell\WindowsApps]
        '''&quot;MUIVerb&quot;=&quot;Windows Apps&quot;
        '''&quot;SubCommands&quot;=&quot;calc;chmap;cmd;dfrg;ie;notepad;paint;psr;snip;srd;srt;tsch;wmp;wordpad&quot;
        '''&quot;icon&quot;=&quot;imageres.dll,152&quot;
        '''&quot;Position&quot;=-
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\calc]
        '''@=&quot;Calculator&quot;
        '''&quot;icon&quot;=&quot;calc.exe&quot;
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\calc\command]
        '''@=&quot;calc.exe&quot;
        '''
        '''[HK [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WindowsApps() As String
            Get
                Return ResourceManager.GetString("WindowsApps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property wkernelbase() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("wkernelbase", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property wntdll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("wntdll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
